// packages/angular-standalone-test-app/src/preview-examples/pill-variants.ts
/*
 * SPDX-FileCopyrightText: 2025 Siemens AG
 *
 * SPDX-License-Identifier: MIT
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 */

import { Component } from '@angular/core';
import {
  IxLayoutGrid,
  IxRow,
  IxCol,
  IxPill,
} from '@siemens/ix-angular/standalone';

@Component({
  selector: 'app-example',
  imports: [IxLayoutGrid, IxRow, IxCol, IxPill],
  styleUrls: ['./pill-variants.css'],
  template: `
    <ix-layout-grid>
      @for (row of pillVariants; track row.variant) {
        <ix-row>
          <ix-col>
            <ix-pill [attr.variant]="row.variant" icon="info">{{
              row.label
            }}</ix-pill>
          </ix-col>
          <ix-col>
            <ix-pill
              [attr.variant]="row.variant"
              outline
              icon="info"
            >{{ row.label }}</ix-pill>
          </ix-col>
        </ix-row>
      }
      <ix-row>
        <ix-col>
          <ix-pill
            variant="custom"
            pill-color="white"
            background="purple"
            icon="info"
          >Custom</ix-pill>
        </ix-col>
        <ix-col>
          <ix-pill
            variant="custom"
            outline
            pill-color="white"
            background="purple"
            icon="info"
          >Custom</ix-pill>
        </ix-col>
      </ix-row>
    </ix-layout-grid>
  `,
})
export default class Pill {
  protected readonly pillVariants = [
    { variant: 'primary', label: 'Primary' },
    { variant: 'alarm', label: 'Alarm' },
    { variant: 'critical', label: 'Critical' },
    { variant: 'warning', label: 'Warning' },
    { variant: 'info', label: 'Info' },
    { variant: 'neutral', label: 'Neutral' },
    { variant: 'success', label: 'Success' },
  ] as const;
}

// packages/vue-test-app/src/preview-examples/pill-variants.vue
<!--
 * SPDX-FileCopyrightText: 2024 Siemens AG
 *
 * SPDX-License-Identifier: MIT
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
-->

<script setup lang="ts">
import { iconInfo } from '@siemens/ix-icons/icons';
import { IxCol, IxLayoutGrid, IxPill, IxRow } from '@siemens/ix-vue';

const pillVariants = [
  { variant: 'primary' as const, label: 'Primary' },
  { variant: 'alarm' as const, label: 'Alarm' },
  { variant: 'critical' as const, label: 'Critical' },
  { variant: 'warning' as const, label: 'Warning' },
  { variant: 'info' as const, label: 'Info' },
  { variant: 'neutral' as const, label: 'Neutral' },
  { variant: 'success' as const, label: 'Success' },
];
</script>

<style scoped src="./pill-variants.css"></style>

<template>
  <IxLayoutGrid>
    <IxRow v-for="row in pillVariants" :key="row.variant">
      <IxCol>
        <IxPill :variant="row.variant" :icon="iconInfo">{{ row.label }}</IxPill>
      </IxCol>
      <IxCol>
        <IxPill :variant="row.variant" outline :icon="iconInfo">
          {{ row.label }}
        </IxPill>
      </IxCol>
    </IxRow>

    <IxRow>
      <IxCol>
        <IxPill
          variant="custom"
          pill-color="white"
          background="purple"
          :icon="iconInfo"
        >
          Custom
        </IxPill>
      </IxCol>
      <IxCol>
        <IxPill
          variant="custom"
          outline
          pill-color="white"
          background="purple"
          :icon="iconInfo"
        >
          Custom
        </IxPill>
      </IxCol>
    </IxRow>
  </IxLayoutGrid>
</template>
