// packages/angular-standalone-test-app/src/preview-examples/pill.ts
/*
 * SPDX-FileCopyrightText: 2025 Siemens AG
 *
 * SPDX-License-Identifier: MIT
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 */

import { Component } from '@angular/core';
import { IxPill } from '@siemens/ix-angular/standalone';

@Component({
  selector: 'app-example',
  imports: [IxPill],
  styleUrls: ['./pill.css'],
  template: `
    <ix-pill variant="custom" pill-color="white" background="purple">Label</ix-pill>

    <ix-pill tooltip-text="Custom tooltip text">Label</ix-pill>
    <ix-pill variant="primary" outline tooltip-text>Label</ix-pill>
    <ix-pill class="styled">Label</ix-pill>

    <ix-pill icon="star">Label</ix-pill>
    <ix-pill icon="star" aria-label="Featured"></ix-pill>
    <ix-pill icon="star" class="styled">Label</ix-pill>
    <ix-pill variant="primary" outline alignLeft icon="star" class="styled">Label</ix-pill>

    <ix-pill variant="alarm">Label</ix-pill>
    <ix-pill variant="alarm" class="styled">Label</ix-pill>

    <ix-pill variant="alarm" icon="star">Label</ix-pill>
    <ix-pill variant="alarm" icon="star" class="styled">Label</ix-pill>
    <ix-pill variant="alarm" alignLeft icon="star" class="styled">
      Label
    </ix-pill>
    <ix-pill icon="star" class="styled-ellipsis-4">Label</ix-pill>
    <ix-pill variant="primary" outline icon="star" class="styled-ellipsis-4">Label</ix-pill>
    <ix-pill class="styled-ellipsis-3">Label</ix-pill>
    <ix-pill variant="primary" outline class="styled-ellipsis-3">Label</ix-pill>
  `,
})
export default class Pill {}

// packages/vue-test-app/src/preview-examples/pill.vue
<!--
 * SPDX-FileCopyrightText: 2024 Siemens AG
 *
 * SPDX-License-Identifier: MIT
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
-->

<script setup lang="ts">
import { iconStar } from '@siemens/ix-icons/icons';
import { IxPill } from '@siemens/ix-vue';
</script>

<style scoped src="./pill.css"></style>

<template>
  <IxPill variant="custom" pill-color="white" background="purple">Label</IxPill>

  <IxPill tooltip-text="Custom tooltip text">Label</IxPill>
  <IxPill class="styled">Label</IxPill>

  <IxPill :icon="iconStar">Label</IxPill>
  <IxPill :icon="iconStar" aria-label="Featured"></IxPill>
  <IxPill :icon="iconStar" class="styled">Label</IxPill>
  <IxPill variant="primary" outline alignLeft :icon="iconStar" class="styled">Label</IxPill>

  <IxPill variant="alarm">Label</IxPill>
  <IxPill variant="alarm" class="styled">Label</IxPill>

  <IxPill variant="alarm" :icon="iconStar">Label</IxPill>
  <IxPill variant="alarm" :icon="iconStar" class="styled">Label</IxPill>
  <IxPill variant="alarm" alignLeft :icon="iconStar" class="styled">
    Label
  </IxPill>
  <IxPill :icon="iconStar" class="styled-ellipsis-4">Label</IxPill>
  <IxPill variant="primary" outline :icon="iconStar" class="styled-ellipsis-4">Label</IxPill>
  <IxPill class="styled-ellipsis-3">Label</IxPill>
  <IxPill variant="primary" outline class="styled-ellipsis-3">Label</IxPill>
</template>
