// packages/angular-test-app/src/preview-examples/tab-panels.ts
/*
 * SPDX-FileCopyrightText: 2026 Siemens AG
 *
 * SPDX-License-Identifier: MIT
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 */

import { Component } from '@angular/core';

@Component({
  standalone: false,
  selector: 'app-example',
  template: `
    <div class="tabs">
      <ix-tab-panels>
        <ix-tabs
          [activeTabKey]="activeTabKey"
          layout="auto"
          (tabChange)="activeTabKey = $event.detail ?? 'tab-1'"
        >
          <ix-tab-item tabKey="tab-1" label="Tab 1"></ix-tab-item>
          <ix-tab-item tabKey="tab-2" label="Tab 2"></ix-tab-item>
          <ix-tab-item tabKey="tab-3" label="Tab 3"></ix-tab-item>
        </ix-tabs>

        <ix-tab-panel tabKey="tab-1">Content 1</ix-tab-panel>
        <ix-tab-panel tabKey="tab-2">Content 2</ix-tab-panel>
        <ix-tab-panel tabKey="tab-3">Content 3</ix-tab-panel>
      </ix-tab-panels>
    </div>
  `,
  styleUrls: ['./tabs.css'],
})
export default class TabPanels {
  activeTabKey = 'tab-2';
}

// packages/vue-test-app/src/preview-examples/tab-panels.vue
<!--
 * SPDX-FileCopyrightText: 2026 Siemens AG
 *
 * SPDX-License-Identifier: MIT
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
-->

<script setup lang="ts">
import { IxTabItem, IxTabPanel, IxTabPanels, IxTabs } from '@siemens/ix-vue';
import { ref } from 'vue';

const activeTabKey = ref('tab-2');

const setActiveTabKey = (event: CustomEvent<string | undefined>) => {
  activeTabKey.value = event.detail ?? 'tab-1';
};
</script>

<template>
  <IxTabPanels>
    <IxTabs
      :activeTabKey="activeTabKey"
      layout="auto"
      @tabChange="setActiveTabKey"
    >
      <IxTabItem tabKey="tab-1" label="Tab 1"></IxTabItem>
      <IxTabItem tabKey="tab-2" label="Tab 2"></IxTabItem>
      <IxTabItem tabKey="tab-3" label="Tab 3"></IxTabItem>
    </IxTabs>

    <IxTabPanel tabKey="tab-1">
      <div>Content 1</div>
    </IxTabPanel>
    <IxTabPanel tabKey="tab-2">
      <div>Content 2</div>
    </IxTabPanel>
    <IxTabPanel tabKey="tab-3">
      <div>Content 3</div>
    </IxTabPanel>
  </IxTabPanels>
</template>
