// packages/react-test-app/src/preview-examples/datetimepicker-min-max-time.tsx
/*
 * SPDX-FileCopyrightText: 2026 Siemens AG
 *
 * SPDX-License-Identifier: MIT
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 */

import { IxDatetimePicker } from '@siemens/ix-react';

export default () => {
  return (
    <IxDatetimePicker
      from="2026/04/18"
      time="12:00:00"
      minTime="09:00:00"
      maxTime="17:30:00"
    />
  );
};

// packages/angular-standalone-test-app/src/preview-examples/datetimepicker-min-max-time.ts
/*
 * SPDX-FileCopyrightText: 2026 Siemens AG
 *
 * SPDX-License-Identifier: MIT
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 */

import { Component } from '@angular/core';
import { IxDatetimePicker } from '@siemens/ix-angular/standalone';

@Component({
  selector: 'app-example',
  imports: [IxDatetimePicker],
  templateUrl: './datetimepicker-min-max-time.html',
})
export default class DatetimepickerMinMaxTime {}
