// packages/react-test-app/src/preview-examples/modal-non-blocking.tsx
/*
 * SPDX-FileCopyrightText: 2024 Siemens AG
 *
 * SPDX-License-Identifier: MIT
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 */

import {
  IxButton,
  IxModalContent,
  IxModalFooter,
  IxModalHeader,
  IxTypography,
  Modal,
  ModalRef,
  showModal,
} from '@siemens/ix-react';
import { useRef } from 'react';

function CustomModal() {
  const modalRef = useRef<ModalRef>(null);

  const close = () => {
    modalRef.current?.close('close payload!');
  };
  const dismiss = () => {
    modalRef.current?.dismiss('dismiss payload');
  };

  return (
    <Modal ref={modalRef} isNonBlocking disableEscapeClose={false}>
      <IxModalHeader onCloseClick={() => dismiss()}>
        Message headline
      </IxModalHeader>
      <IxModalContent>Message text lorem ipsum</IxModalContent>
      <IxModalFooter>
        <IxButton variant="subtle-primary" onClick={() => dismiss()}>
          Cancel
        </IxButton>
        <IxButton onClick={() => close()} autoFocus>
          OK
        </IxButton>
      </IxModalFooter>
    </Modal>
  );
}

export default function ModalNonBlockingPreview() {
  async function show() {
    await showModal({
      content: <CustomModal />,
    });
  }

  return (
    <div>
      <div style={{ padding: '1rem' }}>
        <IxTypography format="body" textColor="std">
          Content behind the dialog
        </IxTypography>
        <IxButton id="behind">Behind control</IxButton>
      </div>
      <IxButton onClick={show}>Show non-blocking modal</IxButton>
    </div>
  );
}

// packages/angular-test-app/src/preview-examples/modal-non-blocking.ts
/*
 * SPDX-FileCopyrightText: 2024 Siemens AG
 *
 * SPDX-License-Identifier: MIT
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 */

import { Component } from '@angular/core';
import { IxActiveModal } from '@siemens/ix-angular';
import { ModalService } from '@siemens/ix-angular';

@Component({
  standalone: false,
  selector: 'app-modal-non-blocking-content',
  template: `
    <ix-modal-header (closeClick)="activeModal.dismiss('dismiss payload')">
      Message headline
    </ix-modal-header>
    <ix-modal-content>Message text lorem ipsum</ix-modal-content>
    <ix-modal-footer>
      <ix-button
        variant="subtle-primary"
        (click)="activeModal.dismiss('dismiss payload')"
      >
        Cancel
      </ix-button>
      <ix-button autofocus (click)="activeModal.close('close payload!')">
        OK
      </ix-button>
    </ix-modal-footer>
  `,
})
export class ModalNonBlockingContent {
  constructor(readonly activeModal: IxActiveModal) {}
}

@Component({
  standalone: false,
  selector: 'app-example',
  template: `
    <div>
      <div style="padding: 1rem">
        <ix-typography format="body" text-color="std">
          Content behind the dialog
        </ix-typography>
        <ix-button id="behind">Behind control</ix-button>
      </div>
      <ix-button (click)="openModal()">Show non-blocking modal</ix-button>
    </div>
  `,
})
export default class ModalNonBlocking {
  constructor(private readonly modalService: ModalService) {}

  async openModal() {
    await this.modalService.open({
      content: ModalNonBlockingContent,
      isNonBlocking: true,
    });
  }
}
