// packages/angular-test-app/src/preview-examples/timepicker-min-max-time.ts
/*
 * SPDX-FileCopyrightText: 2026 Siemens AG
 *
 * SPDX-License-Identifier: MIT
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 */

import { Component } from '@angular/core';
import { IxTimePicker } from '@siemens/ix-angular/standalone';

@Component({
  standalone: true,
  selector: 'app-example',
  imports: [IxTimePicker],
  templateUrl: './timepicker-min-max-time.html',
})
export default class TimepickerMinMaxTime {}

// packages/react-test-app/src/preview-examples/timepicker-min-max-time.tsx
/*
 * SPDX-FileCopyrightText: 2026 Siemens AG
 *
 * SPDX-License-Identifier: MIT
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 */

import { IxTimePicker } from '@siemens/ix-react';

export default () => {
  return (
    <IxTimePicker
      format="HH:mm:ss"
      time="12:00:00"
      minTime="09:00:00"
      maxTime="17:30:00"
    />
  );
};
